source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gemspec

gem "trueskill",
  git: "https://github.com/benjaminleesmith/trueskill",
  ref: "e404f45af5b3fb86982881ce064a9c764cc6a901"
