development: &DEVELOPMENT
  adapter: postgresql
  database: sportsball_development
  host: localhost
  pool: 5
  timeout: 5000

test: &TEST
  <<: *DEVELOPMENT
  database: sportsball_test
  min_messages: warning

production:
  adapter: postgresql
  database: igxzyizr
  username: igxzyizr
  password: CROKAVQ4GVVhbTcJhwLry0CM4nWw0aKF
  host: baasu-01.db.elephantsql.com