# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 384ae611e0717bd4127d682e9f3d73ee8004d5f7f7707c3e6e44a0339e6d5db8b7124076a61865058f197ac4d8d950b0779c11726092965b3c44bccec59265de

test:
  secret_key_base: f48d413b8f5ef763d0bb67252f4a8b268bd9d464e1550f19e2ee842080d8859574b20167758948975f014c2d23d409e395404c82bc0f48398c65785b2b9936fc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
