# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 37ff2d82bb76f8bd8997427a76dedddead8813922028a41de3a75023b66ec0ec82e28c5ebc4d6e166e2af20c750bc89ea590cb058263f40b73b7f7fb437185f2

test:
  secret_key_base: 95c1d042aab2346fa8dbd819adc8dd853ee7e1c05322e5f4947ad38382f637ae99e81615e619802998e9c0231368cb8b64099adf77cc93c60cbc3f5a6c755d5a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
